/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "ADC_DelSig_1.h"
#include "Vin_aliases.h"
#include "Vin.h"
#include "UART_1.h"
#include "ADC_isr.h"
#include "Timer.h"
#include "Timer_isr.h"
#include "I2C_1.h"
#include "I2C_1_PVT.h"
#include "RST_1_aliases.h"
#include "RST_1.h"
#include "SDA_1_aliases.h"
#include "SDA_1.h"
#include "I2C_Clock.h"
#include "SCL_1_aliases.h"
#include "SCL_1.h"
#include "SPIM_1.h"
#include "SPIM_1_PVT.h"
#include "SPI_Clock.h"
#include "MISO_aliases.h"
#include "MISO.h"
#include "CS_aliases.h"
#include "CS.h"
#include "CLK_aliases.h"
#include "CLK.h"
#include "ADC_DelSig_1_AMux.h"
#include "ADC_DelSig_1_Ext_CP_Clk.h"
#include "ADC_DelSig_1_IRQ.h"
#include "ADC_DelSig_1_theACLK.h"
#include "UART_1_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

